---
title: "Refugee Migration"
author: "Julia Bloom"
date: "October 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(rnoaa)
library(devtools)
library(tidyverse)
library(dplyr)
library(maps)
library(ggmap)
library(gganimate)
library(ggthemes)
library(ggplot2)
library(tibble)
library(lubridate)
library(gifski)
library(png)
library(gganimate)
library(spdep)
library(maptools)
library(rgdal)
library(spgwr)
library(ggplot2)
library(leaflet)
require(RColorBrewer)
library(rgdal)
library(plyr)
```

```{r}
migration_df <- read.csv(file.choose(),header=TRUE,check.names=FALSE) ##choose number_refugees_countryoforigon_byyear.csv located in the google doc
temp <- read.csv(file.choose(),header=TRUE,check.names=FALSE, row.names=NULL) ##choose anomoly dataset
```

```{r}
origin_c <- c("Nigeria", "Nepal", "Niger", "Chad", "Chad", "Kenya", "Uganda", "Mali", "Ethiopia", "Bangladesh", "Somalia")

settlements_bycountry <- migration_df %>%
  filter(Origin == origin_c)

settlements_bycountry$Origin <- tolower(settlements_bycountry$Origin)
```

```{r}
names(temp)[names(temp)=="country"] <- "Origin"
```

```{r}
combo <- merge(settlements_bycountry,temp,by = c("Origin", "Year"))
```

